### PR TITLE
New WMTS sources

### PR DESCRIPTION
**Pull request by cedricmoullet**

### CODE REVIEW

**Comment by cedricmoullet** [comment]
@hpchrist Is it what you want for the API3 ?

**Comment by hpchrist** [comment]
Hi @cedricmoullet Yes, this is correct, but don't merge the pull request right now, since the WAF seems to be unstable and we therefore don't want to send more requests to it.

**Comment by gjn** [comment]
@hpchrist I remember why we went back to 5-9 back in June: it was not working then, so we switched back to the non-waf urls.

At the same time, we kept an api version in place to test the waf, those are still active.
`mode=waf` points to http://wmts{0-4}.prod.bgdi.ch
`mode=wafint` points to http://wmts{0-4}.int.bgdi.ch/

It's been 6 months since then...

**Comment by hpchrist** [comment]
Yes, *we* switched back from WAF to NON-WAF. But there was a misunderstanding, obviously, because:

*YOU* switched back in the "code"
*I* switched back in the "DNS"

Same target, other instruments;-)...

**Pull request closed without merging**
