### PR TITLE
Update to latest OL3 master

### PR DESCRIPTION
**Pull request by cedricmoullet**

### CODE REVIEW

**Comment by loicgasser** [comment]
Hi
Here is a [testlink](http://mf-chsdi3.dev.bgdi.ch/gal_update_ol3) in chsdi.
Everything seems to work.

**Comment by ponceta** [comment]
Is it already the 3.1.1 Version?

**Comment by oterral** [comment]
This PR needs to be updated

**Comment by ponceta** [comment]
Added the last commits with @oterral supervision

**Comment by ponceta** [comment]
@loicgasser could you update the test link?

**Comment by ponceta** [comment]
Mmmmh, nevermind, I think it's better to wait until 

https://github.com/openlayers/ol3/pull/3171

is merged and update it again.

**Comment by ponceta** [comment]
Nice choutette super! :)

**Pull request merged**
