### PR TITLE
Update ol 3.6

### PR DESCRIPTION
**Pull request by oterral**
New build system added,

To compile use:
`make -f Makefile-ga build-ga`

To run examples use:
`make -f Makefile-ga serve`

Example available at : http://localhost:3000/build/examples/ga-not-queryable.html

To run hosted examples use:
`make -f Makefile-ga hosted-examples-ga`

Hosted example with compiled version : http://localhost:3000/build/hosted/teo_update_ol_36/examples/ga-not-queryable.html

Hosted example with non-compiled version : http://localhost:3000/build/hosted/teo_update_ol_36/examples/ga-not-queryable.html?mode=raw

### CODE REVIEW

**Comment by oterral** [comment]
@procrastinatio , this one needs  a hudge review :)

**Comment by cedricmoullet** [comment]
@procrastinatio please review 
@oterral How are we goind to provide a test link ?

**Comment by oterral** [comment]
I don't know how to have  test link yet. but ol3.6 is already merge in chsdi3 so I think we can go merge this one.

**Comment by procrastinatio** [comment]
OK, for me.

Still have to update the doc.

**Pull request merged**
